# Generated by Django 4.1.4 on 2022-12-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='desctibe',
            new_name='describe',
        ),
    ]
