# Generated by Django 4.1.4 on 2022-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_desctibe_route_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(default='', upload_to='routes', verbose_name='image'),
            preserve_default=False,
        ),
    ]
