# Generated by Django 4.1.4 on 2022-12-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_desctibe_story_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(
                auto_now_add=True, default="1998-12-12", verbose_name='Date'),
            preserve_default=False,
        ),
    ]
