# Generated by Django 4.1.4 on 2022-12-11 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_story_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
