# Generated by Django 4.1.4 on 2022-12-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_story_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='time',
        ),
    ]
