# Generated by Django 4.1.4 on 2022-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
