# Generated by Django 4.1.4 on 2022-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_story_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='', upload_to='stories', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
